
import {
    Menu,
    MenuButton,
    MenuList,
    MenuItem,
    MenuItemOption,
    MenuGroup,
    MenuOptionGroup,
    MenuDivider,
    Button,
    Card,
  } from '@chakra-ui/react'

  export default function Service(){
    return(
        <Menu>

            <MenuButton className="mt-1 mx-2 block px-2 py-3 text-white font-semibold rounded hover:bg-gray-800 sm:mt-0 sm:ml-2" >
            Service
            </MenuButton>


        <MenuList  minWidth={250} maxWidth={400}>
            <Card className="bg-white text-gray-900 shadow-xl rounded-xl m-3 p-3">
           
                <h1 className='text-center font-bold text-2xl m-2'>Services</h1>
                <hr/>
                <h4 className='font-bold mt-2'>1. Intelligent Quiz Generation</h4>
                <p className='mt-1 ml-2'>Experience dynamic and personalized quizzes generated by advanced artificial intelligence algorithms. Our system adapts to your preferences, creating challenging yet enjoyable quizzes tailored just for you.</p>
                <h4 className='font-bold mt-2'>2. Adaptive Learning Paths</h4>
                <p className='mt-1 ml-2'>QuizBee doesn&#39;t just test your knowledge; it guides your learning journey. Our adaptive learning paths analyze your performance and recommend relevant quizzes to enhance your understanding of specific topics.</p>
                <h4 className='font-bold mt-2'>3. Multi-Domain Quiz Support</h4>
                <p className='mt-1 ml-2'>QuizBee covers a diverse range of subjects and domains. Whether you&#39;re a history buff, science enthusiast, or language aficionado, our app has quizzes to cater to your interests.</p>
                <p className='font-bold text-center mt-2'>Thank you for being a part of QuizBee!</p>
            </Card>
        </MenuList>
</Menu>
    )
  }





